Add AST_json.ml with precise JSON AST (semgrep/semgrep-proprietary#3316)
This will help when writing lockfile parsers; many of them
are stored as JSON files.

test plan:
```
$ ~/zz/bin/semgrep-core-proprietary -dump_lockfile Pipfile.lock
00.06][DEBUG](default): AST = (Assoc
   ((),
    [(("_meta", ()),
      (Assoc
         ((),
          [(("hash", ()),
            (Assoc
               ((),
                [(("sha256", ()),
                  (String
                     ("d50ec359d1920e4ed0cd0f80f9c34542dcd3583535afeadc4c7faf636821820f",
                      ())))
                  ],
                ())));
            (("pipfile-spec", ()), (Float ((Some 6.), ())));
            (("requires", ()), (Assoc ((), [], ())));
            (("sources", ()),
             (Array
                ((),
                 [(Assoc
                     ((),
                      [(("name", ()), (String ("pypi", ())));
                        (("url", ()),
                         (String ("https://pypi.org/simple", ())));
                        (("verify_ssl", ()), (Bool (true, ())))],
                      ()))
                   ],
                 ())))
            ],
          ())));

...
Fatal error: exception Failure: failed to parse Pipfile.lock, error = need to handle version 6.000000.
```

synced from Pro 48506314597e38ff6125158817bf76a2fa7a73aa